version: '2'

services:
  web:
    build: web
    image: dockerdemos/lab-web
    ports: ["80:80"]

  words:
    build: words-dispatcher
    image: dockerdemos/lab-words-dispatcher
    expose: ["8080"]

  words-java:
    build: words-java
    image: dockerdemos/lab-words-java
    expose: ["8080"]

  db-ui:
    image: mongo-express:0.31.0
    ports: ["8081:8081"]

  mongo:
    image: mongo:3.3.15
    expose: ["27017"]
